// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://souibepseqmuoygwxkjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvdWliZXBzZXFtdW95Z3d4a2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODMyNzksImV4cCI6MjA2NTI1OTI3OX0.PTJEY3vkrqsV4Jn3-oi9KesTA-kYbIeyGSmebFDdrZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);